name: 🛡️ New Signature Suggestion
description: Suggest a new PowerShell signature for detection
title: "[SIGNATURE] "
labels: ["enhancement", "signature"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new signature! This helps improve PowerShell security detection for everyone.

  - type: input
    id: signature-name
    attributes:
      label: Signature Name
      description: Proposed name for the signature (UPPERCASE with underscores)
      placeholder: "POWERSHELL_SUSPICIOUS_PATTERN"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this signature belong to?
      options:
        - EXECUTION
        - OBFUSCATION
        - PERSISTENCE
        - PRIVILEGE_ESCALATION
        - DEFENSE_EVASION
        - CREDENTIAL_ACCESS
        - DISCOVERY
        - LATERAL_MOVEMENT
        - COLLECTION
        - EXFILTRATION
        - OTHER
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is the threat this signature detects?
      options:
        - info
        - medium
        - high
        - critical
    validations:
      required: true

  - type: number
    id: score
    attributes:
      label: Risk Score
      description: Risk score (0-100)
      placeholder: "75"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of what this signature detects
      placeholder: "Detects PowerShell technique that..."
    validations:
      required: true

  - type: textarea
    id: regex-pattern
    attributes:
      label: Regex Pattern
      description: The regex pattern for detection (escape special characters)
      placeholder: "New-Object\\s+System\\.Net\\.WebClient"
    validations:
      required: true

  - type: input
    id: regex-flags
    attributes:
      label: Regex Flags
      description: Regex flags to use
      placeholder: "i"
      value: "i"

  - type: textarea
    id: example-commands
    attributes:
      label: Example Malicious Commands
      description: Examples of commands this signature should detect
      placeholder: |
        Example commands that should trigger this signature:
        - Command 1
        - Command 2

  - type: textarea
    id: false-positives
    attributes:
      label: Potential False Positives
      description: Are there any legitimate uses that might trigger this signature?
      placeholder: "Consider legitimate admin scripts that might..."

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any references to techniques, CVEs, or security research
      placeholder: |
        - MITRE ATT&CK: T1059.001
        - Security blog post: https://...
        - CVE: CVE-XXXX-XXXX
